### ISSUE TITLE
Script always crashes when Starting

### ISSUE THREAD

**Issue by jan620** [bb-Ricardo/fritzinfluxdb#43]
When I Start the Exporter with /opt/fritzinfluxdb $ ./fritzinfluxdb.py it tries to start but it crashes always with
INFO: Starting main loop
./fritzinfluxdb.py:141: RuntimeWarning: coroutine 'InfluxHandler.task_loop' was never awaited
  task = loop.create_task(handler.task_loop(queue), name=handler.name)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

and then it closes the connections and after the Shutdown Information I get this:
Traceback (most recent call last):
  File "./fritzinfluxdb.py", line 155, in <module>
    main()
  File "./fritzinfluxdb.py", line 141, in main
    task = loop.create_task(handler.task_loop(queue), name=handler.name)
TypeError: create_task() got an unexpected keyword argument 'name'

**Comment by jan620** [comment]
Yes, here's the Output:
$ python --version
Python 2.7.16

**Comment by bb-Ricardo** [comment]
The minimum python version is 3.6 according to the Readme.

Pleas try again with a never version.

**Comment by jan620** [comment]
Still having the issue, even with python 3.7.3:

pi@iobroker-pi:~ $ python --version
Python 3.7.3
pi@iobroker-pi:~ $ cd /opt/fritzinfluxdb/
pi@iobroker-pi:/opt/fritzinfluxdb $ ./fritzinfluxdb.py
2022-08-05 15:57:40,741 - INFO: Starting fritzinfluxdb v1.0.0 (2022-06-11)
2022-08-05 15:57:40,755 - INFO: Done reading config files
2022-08-05 15:57:41,128 - INFO: Successfully parsed config
2022-08-05 15:57:41,182 - INFO: Connection to InfluxDB 1.8.2 established and database present
2022-08-05 15:57:57,243 - INFO: Successfully established FritzBox TR-069 session
2022-08-05 15:57:58,063 - INFO: Successfully established FritzBox Lua session
2022-08-05 15:57:58,064 - INFO: Successfully connected to FritzBox '192.168.178.1' (fritz.box) Model: FRITZ!Box 7590 AX - FW: 7.31
2022-08-05 15:57:58,067 - INFO: Starting main loop
./fritzinfluxdb.py:141: RuntimeWarning: coroutine 'InfluxHandler.task_loop' was never awaited
  task = loop.create_task(handler.task_loop(queue), name=handler.name)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-08-05 15:57:58,081 - INFO: Closed FritzBox TR-069 connection
2022-08-05 15:57:58,083 - INFO: Closed FritzBox Lua connection
2022-08-05 15:57:58,085 - INFO: Closed InfluxDB session
2022-08-05 15:57:58,085 - INFO: Successfully shutdown fritzinfluxdb
Traceback (most recent call last):
  File "./fritzinfluxdb.py", line 155, in <module>
    main()
  File "./fritzinfluxdb.py", line 141, in main
    task = loop.create_task(handler.task_loop(queue), name=handler.name)
TypeError: create_task() got an unexpected keyword argument 'name'
