### ISSUE TITLE
Failed to start Service,  no module named 'influxdb_client'

### ISSUE THREAD

**Issue by bcsti** [bb-Ricardo/fritzinfluxdb#49]
When i start the script manually, everything works fine.

But when i start the service, following error appears:

Started Fritz to InfluxDB daemon.
fritzinfluxdb[16107]: Traceback (most recent call last):
fritzinfluxdb[16107]:   File "/opt/fritzinfluxdb/fritzinfluxdb.py", line 27, in <module>
fritzinfluxdb[16107]:     from fritzinfluxdb.classes.influxdb.handler import InfluxHandler
fritzinfluxdb[16107]:   File "/opt/fritzinfluxdb/fritzinfluxdb/classes/influxdb/handler.py", line 20, in <module>
fritzinfluxdb[16107]:     from influxdb_client.rest import ApiException
fritzinfluxdb[16107]: ModuleNotFoundError: No module named 'influxdb_client'
systemd[1]: fritzinfluxdb.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: fritzinfluxdb.service: Failed with result 'exit-code'.
systemd[1]: fritzinfluxdb.service: Scheduled restart job, restart counter is at 123.
systemd[1]: Stopped Fritz to InfluxDB daemon.

All requirements are installed, the OS is Raspbian 32 Bit.

**Comment by bb-Ricardo** [comment]
Hi,

It seems the virtual environment where you installed the dependencies can't be found.

Did you use the service file provided?

**Comment by bb-Ricardo** [comment]
This probably won't work dou to the sudo commands used. Did you try changing to a root shell and use the commands in the Readme?

**Comment by bcsti** [comment]
Thanks for the info, it works!
I left the script running, but in grafana no system information is shown (logs, CPU, hosts, IP address, ram, energy, ...), only traffic info. What could be the problem?

**Comment by todrees1967** [comment]
Try to restart the script. I had a similar issue here, due to an outage of the cable internet I have restrted my fritz box and from that time the script couldn't fetch data. Check the logs from fritz box, you might see error messages there as well.

**Comment by bb-Ricardo** [comment]
You can also try to set the log level to DEBUG. There it should print out all the values parsed and sent to influx.

**Comment by bcsti** [comment]
Oh, it looks like my FRITZ!OS version is not supported. I have a FRITZ!Box 7530 AX with FRITZ!OS 07.31

2022-09-08 17:45:51,173 - DEBUG: FritzOS version 7.31 not in list of supported versions for System Stats: ['7.29', '7.39']
2022-09-08 17:45:51,173 - DEBUG: FritzOS version 7.31 not in list of supported versions for Energy Stats: ['7.29', '7.39']
2022-09-08 17:45:51,173 - DEBUG: FritzOS version 7.31 not in list of supported versions for System logs: ['7.29']
2022-09-08 17:45:51,173 - DEBUG: FritzOS version 7.31 not in list of supported versions for System logs: ['7.39']
2022-09-08 17:45:51,174 - DEBUG: FritzOS version 7.31 not in list of supported versions for Internet connection logs: ['7.29']
2022-09-08 17:45:51,174 - DEBUG: FritzOS version 7.31 not in list of supported versions for Internet connection logs: ['7.39']
2022-09-08 17:45:51,174 - DEBUG: FritzOS version 7.31 not in list of supported versions for Telephony logs: ['7.29']
2022-09-08 17:45:51,174 - DEBUG: FritzOS version 7.31 not in list of supported versions for Telephony logs: ['7.39']
2022-09-08 17:45:51,174 - DEBUG: FritzOS version 7.31 not in list of supported versions for WLAN logs: ['7.29']
2022-09-08 17:45:51,175 - DEBUG: FritzOS version 7.31 not in list of supported versions for WLAN logs: ['7.39']
2022-09-08 17:45:51,175 - DEBUG: FritzOS version 7.31 not in list of supported versions for USB Devices logs: ['7.29']
2022-09-08 17:45:51,175 - DEBUG: FritzOS version 7.31 not in list of supported versions for USB Devices logs: ['7.39']
2022-09-08 17:45:51,175 - DEBUG: FritzOS version 7.31 not in list of supported versions for Active network hosts: ['7.29', '7.39']
2022-09-08 17:45:51,175 - DEBUG: FritzOS version 7.31 not in list of supported versions for Passive network hosts: ['7.29', '7.39']
2022-09-08 17:45:51,176 - DEBUG: FritzOS version 7.31 not in list of supported versions for VPN Users: ['7.29']
2022-09-08 17:45:51,176 - DEBUG: FritzOS version 7.31 not in list of supported versions for VPN Users: ['7.39']
2022-09-08 17:45:51,176 - DEBUG: FritzOS version 7.31 not in list of supported versions for DSL Info: ['7.29', '7.39']
2022-09-08 17:45:51,176 - DEBUG: FritzOS version 7.31 not in list of supported versions for Cable Info: ['7.29', '7.39']

**Comment by bb-Ricardo** [comment]
Ui, was not aware of 7.30 nor 7.31. Just add 7.31 to all services which have 7.29 in this file: https://github.com/bb-Ricardo/fritzinfluxdb/blob/master/fritzinfluxdb/classes/fritzbox/services_lua.py

let me know if it works or where it throws issues. Then I can officially add it to repo. Thant would be awesome.
thank you.

**Comment by bcsti** [comment]
Yeah, everything works fine now, only the IP-Information is missing. (But i dont know if it works at all)
![grafik](https://user-images.githubusercontent.com/92046752/189184937-8bcd6bac-8e79-435e-8a0e-9a7236ee8119.png)


FYI, this are the current versions for Cable and DSL:

![grafik](https://user-images.githubusercontent.com/92046752/189185556-64493331-0eba-4d6f-b4c4-93a452d0fa32.png)

**Comment by bcsti** [comment]
Here is the log:

2022-09-08 18:29:53,487 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:53,487 - DEBUG: Request FritzBox Lua service 'System Stats' returned successfully
2022-09-08 18:29:53,787 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:53,788 - DEBUG: Request FritzBox Lua service 'Energy Stats' returned successfully
2022-09-08 18:29:54,189 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:54,190 - DEBUG: Request FritzBox Lua service 'System logs' returned successfully
2022-09-08 18:29:54,236 - DEBUG: FritzOS version 7.31 not in list of supported versions for System logs: ['7.39']
2022-09-08 18:29:54,526 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:54,526 - DEBUG: Request FritzBox Lua service 'Internet connection logs' returned successfully
2022-09-08 18:29:54,528 - DEBUG: FritzOS version 7.31 not in list of supported versions for Internet connection logs: ['7.39']
2022-09-08 18:29:54,832 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:54,832 - DEBUG: Request FritzBox Lua service 'Telephony logs' returned successfully
2022-09-08 18:29:54,832 - DEBUG: FritzOS version 7.31 not in list of supported versions for Telephony logs: ['7.39']
2022-09-08 18:29:55,125 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:55,126 - DEBUG: Request FritzBox Lua service 'WLAN logs' returned successfully
2022-09-08 18:29:55,128 - DEBUG: FritzOS version 7.31 not in list of supported versions for WLAN logs: ['7.39']
2022-09-08 18:29:55,405 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:55,406 - DEBUG: Request FritzBox Lua service 'USB Devices logs' returned successfully
2022-09-08 18:29:55,406 - DEBUG: FritzOS version 7.31 not in list of supported versions for USB Devices logs: ['7.39']
2022-09-08 18:29:55,911 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:55,912 - DEBUG: Request FritzBox Lua service 'Active network hosts' returned successfully
2022-09-08 18:29:56,414 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:56,415 - DEBUG: Request FritzBox Lua service 'Passive network hosts' returned successfully
2022-09-08 18:29:56,659 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:56,660 - DEBUG: Request FritzBox Lua service 'VPN Users' returned successfully
2022-09-08 18:29:56,662 - DEBUG: FritzOS version 7.31 not in list of supported versions for VPN Users: ['7.39']
2022-09-08 18:29:57,419 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:57,419 - DEBUG: Request FritzBox Lua service 'DSL Info' returned successfully
2022-09-08 18:29:58,407 - DEBUG: FritzBox Lua request successful
2022-09-08 18:29:58,408 - INFO: Unable to request FritzBox Lua service 'Cable Info'
2022-09-08 18:29:58,408 - INFO: FritzBox Lua service 'Cable Info' will be disabled.

**Comment by bb-Ricardo** [comment]
> Yeah, everything works fine now, only the IP-Information is missing. (But i dont know if it works at all) ![grafik](https://user-images.githubusercontent.com/92046752/189184937-8bcd6bac-8e79-435e-8a0e-9a7236ee8119.png)
> 
> FYI, this are the current versions for Cable and DSL:
> 
> ![grafik](https://user-images.githubusercontent.com/92046752/189185556-64493331-0eba-4d6f-b4c4-93a452d0fa32.png)

The IP addresses should be provided via TR69 protocol.

Where did you get this neat overview of FritzBox models and their versions?

**Comment by bcsti** [comment]
I have the protocol activated.

![Screenshot_20220909-221440~2](https://user-images.githubusercontent.com/92046752/189472206-65e4e266-0ce4-4e20-84fa-c4b5cf6aebc6.png)

The overview is a text file I made as a comparison for my fritzbox and updated for you. The info comes from the AVM website.

**Comment by bcsti** [comment]
I have tested the next-release branch and had no issues so far. Good job!
